name: PacketsTutorialProtocolLib
version: ${project.version}
main: me.kodysimpson.packetstutorialprotocollib.PacketsTutorialProtocolLib
api-version: 1.17
depend: [ProtocolLib]
commands:
  boom:
    description: yeet